// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	NickName  string `json:"nick_name"`  // 昵称
	AvatarUrl string `json:"avatar_url"` // 头像地址
}

type Video struct {
	Id         int64  `json:"id"`          // 视频ID
	PlayUrl    string `json:"play_url"`    // 视频播放地址
	ThumbUrl   string `json:"thumb_url"`   // 视频封面地址
	Title      string `json:"title"`       // 视频标题
	FavNum     int64  `json:"fav_num"`     // 点赞数
	CommentNum int64  `json:"comment_num"` // 评论数
	ShareNum   int64  `json:"share_num"`   // 分享数
	IsFav      bool   `json:"is_fav"`      // 当前用户是否已点赞
	IsFollow   bool   `json:"is_follow"`   // 当前用户是否已关注该用户
	Author     User   `json:"author"`      // 作者信息
}

type FeedReq struct {
	LatestTime int64  `json:"latest_time,optional"` // 最新视频时间(毫秒时间戳)
	Token      string `json:"token,optional"`       // 用户token
}

type FeedResp struct {
	VideoList []*Video `json:"video_list"`
	NextTime  int64    `json:"next_time"` // 下次请求时间(毫秒时间戳)
}
