version: "3"

services:
  etcd:
    container_name: "flickFrame-etcd"
    image: bitnami/etcd:latest
    restart: always
    networks:
      - flickFrame
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
  oss-rpc:
    container_name: "flickFrame-oss-rpc"
    build:
      context: .
      dockerfile: ./app/oss/rpc/Dockerfile
    networks:
      - flickFrame
    ports:
      - "8081:8081"
networks:
  flickFrame:
    driver: bridge
