// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	feed "github.com/FlickaFrame/FlickaFrame-Server/internal/handler/feed"
	user "github.com/FlickaFrame/FlickaFrame-Server/internal/handler/user"
	"github.com/FlickaFrame/FlickaFrame-Server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: feed.FeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/category",
				Handler: feed.CategoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
