// Code generated by goctl. DO NOT EDIT.
package types

type OssEndpointResponse struct {
	EndPoint string `json:"endpoint"`
}

type CreateUpTokenReq struct {
	UploadType string `form:"uploadType"` // 上传类型(video:视频,cover:封面,avatar:头像)
}

type CreateUpTokenResp struct {
	UpToken string `json:"upToken"` // 上传凭证
	Expires int64  `json:"expires"` // 上传凭证过期时间(秒)
}
